apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-shop-cutomer
spec:
  selector:
    matchLabels:
      app: ctse-shop-cutomer
  template:
    metadata:
      labels:
        app: ctse-shop-cutomer
    spec:
      containers:
        - name: ctse-shop-cutomer
          image: hash151/ctse-shop-cutomer
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
     