apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-shop-customer
spec:
  selector:
    matchLabels:
      app: ctse-shop-customer
  template:
    metadata:
      labels:
        app: ctse-shop-customer
    spec:
      containers:
        - name: ctse-shop-customer
          image: hash151/ctse-shop-customer
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
     